apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
spec:
  containers:
     - name: elasticsearch
       image: "docker.elastic.co/elasticsearch/elasticsearch:7.3.0"
       ports:
         - containerPort: 9200
       imagePullPolicy: Always
