apiVersion: v1
kind: DeploymentConfig
metadata:
  name: elasticsearch-master
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      containers:
      - name: elasticsearch-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.2"
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "elasticsearch"
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_HEAP_SIZE
          value: "512m"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch-discovery"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage-master
          mountPath: /data
      volumes:
        - name: storage-master
          persistentVolumeClaim:
            claimName: data-node-pvc
