kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: elasticsearch-SecurityContextConstraints
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowedCapabilities:
  - IPC_LOCK
  - SYS_RESOURCE
