apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-node-persistence-volume
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
