apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-node-pvc
  labels:
    component: elasticsearch
    target: master
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
    selector:
      matchLabels:
        component: elasticsearch
