apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data-elasticsearch-data-statefull-0
  labels:
    component: elasticsearch
    target: master
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
    selector:
      matchLabels:
        component: elasticsearch
